const members=[
{slug:'fuma',no:'01',name:'ふまふま。',roman:'FUMAFUMA',color:'#7baa17',image:'assets/fuma.png',smile:'assets/fuma-smile.png',x:'https://x.com/Fumafuma_kero',bio:'ブビトラを彩る、緑担当メンバー。配信やグループ企画で活動中。',tags:['VTUBER','STREAM','BOOBY TRAPS']},
{slug:'kuroyan',no:'02',name:'黒ヤン',roman:'KUROYAN',color:'#F79428',image:'assets/kuroyan.png',smile:'assets/kuroyan-smile.png',x:'https://x.com/KuroYan_1113',bio:'ブビトラのオレンジ担当メンバー。配信やグループ企画で活動中。',tags:['VTUBER','STREAM','BOOBY TRAPS']},
{slug:'poke',no:'03',name:'ぽけぷりん',roman:'POKEPURIN',color:'#FFE500',image:'assets/poke.png',smile:'assets/poke-smile.png',x:'https://x.com/pokepurin0701',youtube:'https://www.youtube.com/@pokepurin0701',twitch:'https://www.twitch.tv/pokepurin0701',goods:'https://pokepurin.booth.pm/',bio:'ブビトラのマスコットの生みの親。Live2Dやイラスト、公式サイト制作など、クリエイティブ全般を担当する破天荒なボケ担当。今年の収益化を目指して、日々奮闘中！',tags:['SHORTS','VALORANT','SING']},
{slug:'oranjina',no:'04',name:'おらんじ～な',roman:'ORANJINA',color:'#CC4F33',image:'assets/oranjina.png',smile:'assets/oranjina-smile.png',x:'https://x.com/0RaNge117',twitch:'https://www.twitch.tv/0RaNge117',bio:'ブビトラのおらんじ～な。ゲーム配信やコラボで活動中。',tags:['GAME','STREAM','BOOBY TRAPS']},
{slug:'shoyu',no:'05',name:'しょ～ゆ',roman:'SHOYU',color:'#3864a2',image:'assets/shoyu.png',smile:'assets/shoyu-smile.png',x:'https://x.com/syoyu3desu',bio:'配信やゲーム実況を中心に活動する、青担当メンバー。',tags:['GAME','YOUTUBE','TWITCH']},
{slug:'ruka',no:'06',name:'るかぴのぴ',roman:'RUKAPINOPI',color:'#e23d28',image:'assets/ruka.png',smile:'assets/ruka-smile.png',x:'https://x.com/rukasan_dayo',youtube:'https://www.youtube.com/@Rukasan_dayo',bio:'FF14とVALORANTを中心に、歌ってみたでも活動する赤担当メンバー。',tags:['FF14','VALORANT','SING']}
];
const character=(m,profile=false)=>`<div class="${profile?'profile-visual':'member-image'}" ${profile?'tabindex="0"':''}><img class="normal" src="${m.image}" alt="${m.name}の通常表情"><img class="smile" src="${m.smile}" alt="${m.name}の笑顔" aria-hidden="true"><span class="${profile?'profile-number':''}">${m.no}</span></div>`;
document.querySelector('#memberGrid').innerHTML=members.map(m=>`<a class="member-card" href="#member/${m.slug}" style="--member:${m.color}">${character(m)}<div class="member-name"><b>${m.name}</b><small>${m.roman}</small><i>↗</i></div></a>`).join('');
function route(){const slug=location.hash.startsWith('#member/')?location.hash.slice(8):'';const m=members.find(x=>x.slug===slug);const home=document.querySelector('#homePage'),profile=document.querySelector('#profilePage');if(!m){home.hidden=false;profile.hidden=true;return}const i=members.indexOf(m),next=members[(i+1)%members.length];const links=[['X / TWITTER',m.x],['YOUTUBE',m.youtube],['TWITCH',m.twitch],['SHOP',m.goods]].filter(x=>x[1]);profile.style.setProperty('--member',m.color);profile.innerHTML=`<header class="profile-nav"><a href="#members">← BOOBY TRAPS</a><span>${m.no} / 06</span></header><section class="profile-hero">${character(m,true)}<div class="profile-copy"><p class="kicker">BOOBY TRAPS MEMBER</p><h1>${m.roman}</h1><h2>${m.name}</h2><div class="color-line"></div><p>${m.bio}</p><div class="tag-list">${m.tags.map(t=>`<span>#${t}</span>`).join('')}</div><div class="profile-links">${links.map(([label,href])=>`<a href="${href}" target="_blank" rel="noreferrer">${label}<b>↗</b></a>`).join('')}</div></div></section><section class="profile-bottom"><a href="#members">← 6人のメンバー一覧</a><a href="#member/${next.slug}">NEXT：${next.name} →</a></section>`;home.hidden=true;profile.hidden=false;scrollTo(0,0)}
addEventListener('hashchange',route);route();
